packages:
  - site
  - studio
  - seed

peerDependencyRules:
  allowedVersions:
    '@sanity/astro>@sanity/client': '8'
    '@sanity/preview-url-secret>@sanity/client': '8'
  ignoreMissing:
    - sanity
    - styled-components
    - react-is

allowBuilds:
  esbuild: true
  workerd: true

minimumReleaseAgeExclude:
  - concurrently@10.0.5

onlyBuiltDependencies:
  - esbuild
  - workerd
