/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Action = {
  _type: "action";
  label?: string;
  href?: string;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  kicker?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  statement?: string;
  body?: Array<string>;
  charm?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  actions?: Array<
    {
      _key: string;
    } & Action
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brand?: string;
  tagline?: string;
  email?: string;
  instagram?: string;
  instagramHandle?: string;
  copyright?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Action
  | LegalPage
  | Slug
  | SanityImageAssetReference
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../site/src/lib/content.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    brand, tagline, email, instagram, instagramHandle, copyright,    seo{title, description, ogImage}  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      brand: null;
      tagline: null;
      email: null;
      instagram: null;
      instagramHandle: null;
      copyright: null;
      seo: null;
    }
  | {
      brand: string | null;
      tagline: string | null;
      email: string | null;
      instagram: string | null;
      instagramHandle: string | null;
      copyright: string | null;
      seo: {
        title: string | null;
        description: string | null;
        ogImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      } | null;
    }
  | null;

// Source: ../site/src/lib/content.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    heading, statement, body,    charm{alt, asset},    actions[]{_key, label, href}  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      heading: null;
      statement: null;
      body: null;
      charm: null;
      actions: null;
    }
  | {
      heading: null;
      statement: null;
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      charm: null;
      actions: null;
    }
  | {
      heading: string | null;
      statement: string | null;
      body: Array<string> | null;
      charm: {
        alt: string | null;
        asset: SanityImageAssetReference | null;
      } | null;
      actions: Array<{
        _key: string;
        label: string | null;
        href: string | null;
      }> | null;
    }
  | null;

// Source: ../site/src/lib/content.ts
// Variable: LEGAL_PAGE_SLUGS_QUERY
// Query: *[_type == "legalPage" && defined(slug.current)].slug.current
export type LEGAL_PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../site/src/lib/content.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == "legalPage" && slug.current == $slug][0]{    title, kicker, body, "slug": slug.current  }
export type LEGAL_PAGE_QUERY_RESULT = {
  title: string | null;
  kicker: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    brand, tagline, email, instagram, instagramHandle, copyright,\n    seo{title, description, ogImage}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    heading, statement, body,\n    charm{alt, asset},\n    actions[]{_key, label, href}\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "legalPage" && defined(slug.current)].slug.current\n': LEGAL_PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "legalPage" && slug.current == $slug][0]{\n    title, kicker, body, "slug": slug.current\n  }\n': LEGAL_PAGE_QUERY_RESULT;
  }
}
