/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  language?: 'en' | 'de'
  noIndex?: boolean
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Action = {
  _type: 'action'
  linkType?: 'internal' | 'external'
  page?: PageReference
  href?: string
  label?: string
}

export type Cta = {
  _type: 'cta'
  heading?: string
  body?: string
  actions?: Array<
    {
      _key: string
    } & Action
  >
  background?: 'normal' | 'akzent'
}

export type Gallery = {
  _type: 'gallery'
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  columns?: '2' | '3'
}

export type ImageText = {
  _type: 'imageText'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  heading?: string
  body?: string
  actions?: Array<
    {
      _key: string
    } & Action
  >
  imagePosition?: 'links' | 'rechts'
  background?: 'normal' | 'sand' | 'akzent'
}

export type RichText = {
  _type: 'richText'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h2'
    listItem?: 'bullet'
    markDefs?: Array<
      {
        _key: string
      } & Link
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  width?: 'schmal' | 'breit'
}

export type Hero = {
  _type: 'hero'
  heading?: string
  statement?: string
  body?: Array<string>
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imagePosition?: 'links' | 'rechts'
  actions?: Array<
    {
      _key: string
    } & Action
  >
}

export type PageBuilder = Array<
  | ({
      _key: string
    } & Hero)
  | ({
      _key: string
    } & RichText)
  | ({
      _key: string
    } & ImageText)
  | ({
      _key: string
    } & Gallery)
  | ({
      _key: string
    } & Cta)
>

export type Link = {
  _type: 'link'
  linkType?: 'internal' | 'external'
  page?: PageReference
  href?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  pageBuilder?: PageBuilder
  seo?: Seo
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  pageBuilder?: PageBuilder
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  brand?: string
  tagline?: string
  email?: string
  instagram?: string
  instagramHandle?: string
  copyright?: string
  backLabel?: string
  instagramLabel?: string
  headerLinks?: Array<
    {
      _key: string
    } & Action
  >
  footerLinks?: Array<
    {
      _key: string
    } & Action
  >
  notFound?: {
    heading?: string
    body?: string
  }
  seo?: Seo
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | PageReference
  | Action
  | Cta
  | Gallery
  | ImageText
  | RichText
  | Hero
  | PageBuilder
  | Link
  | Page
  | Slug
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../site/src/lib/content.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings" && _type == "siteSettings"][0]{    brand, tagline, email, instagram, instagramHandle, copyright,    backLabel, instagramLabel, notFound{heading, body},    headerLinks[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)},    footerLinks[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)},    seo{title, description, language, noIndex, ogImage{alt, asset}}  }
export type SITE_SETTINGS_QUERY_RESULT = {
  brand: string | null
  tagline: string | null
  email: string | null
  instagram: string | null
  instagramHandle: string | null
  copyright: string | null
  backLabel: string | null
  instagramLabel: string | null
  notFound: {
    heading: string | null
    body: string | null
  } | null
  headerLinks: Array<{
    _key: string
    label: string | null
    href: string | null
  }> | null
  footerLinks: Array<{
    _key: string
    label: string | null
    href: string | null
  }> | null
  seo: {
    title: string | null
    description: string | null
    language: 'de' | 'en' | null
    noIndex: boolean | null
    ogImage: {
      alt: string | null
      asset: SanityImageAssetReference | null
    } | null
  } | null
} | null

// Source: ../site/src/lib/content.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage" && _type == "homePage"][0]{seo{title, description, language, noIndex, ogImage{alt, asset}},   pageBuilder[]{    _key, _type,    _type == "hero" => {heading, statement, body, image{alt, asset}, imagePosition, actions[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}},    _type == "richText" => {content[]{..., markDefs[]{..., _type == "link" => {"href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}}}, width},    _type == "imageText" => {image{alt, asset}, heading, body, imagePosition, background, actions[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}},    _type == "gallery" => {images[]{_key, alt, asset}, columns},    _type == "cta" => {heading, body, background, actions[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}}  }}
export type HOME_PAGE_QUERY_RESULT = {
  seo: {
    title: string | null
    description: string | null
    language: 'de' | 'en' | null
    noIndex: boolean | null
    ogImage: {
      alt: string | null
      asset: SanityImageAssetReference | null
    } | null
  } | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'cta'
        heading: string | null
        body: string | null
        background: 'akzent' | 'normal' | null
        actions: Array<{
          _key: string
          label: string | null
          href: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'gallery'
        images: Array<{
          _key: string
          alt: string | null
          asset: SanityImageAssetReference | null
        }> | null
        columns: '2' | '3' | null
      }
    | {
        _key: string
        _type: 'hero'
        heading: string | null
        statement: string | null
        body: Array<string> | null
        image: {
          alt: string | null
          asset: SanityImageAssetReference | null
        } | null
        imagePosition: 'links' | 'rechts' | null
        actions: Array<{
          _key: string
          label: string | null
          href: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'imageText'
        image: {
          alt: string | null
          asset: SanityImageAssetReference | null
        } | null
        heading: string | null
        body: string | null
        imagePosition: 'links' | 'rechts' | null
        background: 'akzent' | 'normal' | 'sand' | null
        actions: Array<{
          _key: string
          label: string | null
          href: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'richText'
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'h2' | 'normal'
          listItem?: 'bullet'
          markDefs: Array<{
            _key: string
            _type: 'link'
            linkType?: 'external' | 'internal'
            page?: PageReference
            href: string | null
          }> | null
          level?: number
          _type: 'block'
          _key: string
        }> | null
        width: 'breit' | 'schmal' | null
      }
  > | null
} | null

// Source: ../site/src/lib/content.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>

// Source: ../site/src/lib/content.ts
// Variable: SITEMAP_QUERY
// Query: {  "siteExcluded": coalesce(*[_id == "siteSettings" && _type == "siteSettings"][0].seo.noIndex, false),  "homeExcluded": coalesce(*[_id == "homePage" && _type == "homePage"][0].seo.noIndex, false),  "slugs": *[_type == "page" && defined(slug.current) && seo.noIndex != true].slug.current}
export type SITEMAP_QUERY_RESULT = {
  siteExcluded: boolean | false
  homeExcluded: boolean | false
  slugs: Array<string | null>
}

// Source: ../site/src/lib/content.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title, "slug": slug.current, seo{title, description, language, noIndex, ogImage{alt, asset}},      pageBuilder[]{    _key, _type,    _type == "hero" => {heading, statement, body, image{alt, asset}, imagePosition, actions[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}},    _type == "richText" => {content[]{..., markDefs[]{..., _type == "link" => {"href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}}}, width},    _type == "imageText" => {image{alt, asset}, heading, body, imagePosition, background, actions[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}},    _type == "gallery" => {images[]{_key, alt, asset}, columns},    _type == "cta" => {heading, body, background, actions[defined(select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current))]{_key, "label": coalesce(label, page->title), "href": select(  linkType == "external" => href,  defined(page->slug.current) => "/" + page->slug.current)}}  }  }
export type PAGE_QUERY_RESULT = {
  title: string | null
  slug: string | null
  seo: {
    title: string | null
    description: string | null
    language: 'de' | 'en' | null
    noIndex: boolean | null
    ogImage: {
      alt: string | null
      asset: SanityImageAssetReference | null
    } | null
  } | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'cta'
        heading: string | null
        body: string | null
        background: 'akzent' | 'normal' | null
        actions: Array<{
          _key: string
          label: string | null
          href: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'gallery'
        images: Array<{
          _key: string
          alt: string | null
          asset: SanityImageAssetReference | null
        }> | null
        columns: '2' | '3' | null
      }
    | {
        _key: string
        _type: 'hero'
        heading: string | null
        statement: string | null
        body: Array<string> | null
        image: {
          alt: string | null
          asset: SanityImageAssetReference | null
        } | null
        imagePosition: 'links' | 'rechts' | null
        actions: Array<{
          _key: string
          label: string | null
          href: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'imageText'
        image: {
          alt: string | null
          asset: SanityImageAssetReference | null
        } | null
        heading: string | null
        body: string | null
        imagePosition: 'links' | 'rechts' | null
        background: 'akzent' | 'normal' | 'sand' | null
        actions: Array<{
          _key: string
          label: string | null
          href: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'richText'
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'h2' | 'normal'
          listItem?: 'bullet'
          markDefs: Array<{
            _key: string
            _type: 'link'
            linkType?: 'external' | 'internal'
            page?: PageReference
            href: string | null
          }> | null
          level?: number
          _type: 'block'
          _key: string
        }> | null
        width: 'breit' | 'schmal' | null
      }
  > | null
} | null
